MagicButton/Pages/Action.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MagicButton.Data;
using MagicButton.Data.Models;
using System.Text.Json;

namespace MagicButton.Pages
{
    public class ActionModel : PageModel
    {
        private readonly MagicButton.Data.MagicDbContext _context;

        public ActionModel(MagicButton.Data.MagicDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ActionConfig ActionConfig { get; set; } = default!;
        private async Task PopulateDeviceConfigsAsync()
        {
            ViewData["DeviceConfigId"] = new SelectList(
                await _context.DeviceConfigs
                    .OrderBy(d => d.DeviceId) // or whatever display you prefer
                    .ToListAsync(),
                "Id",
                "DeviceId"
            );
        }
        public async Task<IActionResult> OnGetAsync()
        {
            await PopulateDeviceConfigsAsync();
            
            var id = await _context.ActionConfigs.FirstOrDefaultAsync();

            if (id == null)
            {
                // CREATE mode
                ActionConfig = new ActionConfig
                {
                    // set any sensible defaults here if you want
                };
                return Page();
            }

            // EDIT mode
            ActionConfig = id;

      


            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                await PopulateDeviceConfigsAsync();
                return Page();
            }

            var isNew = ActionConfig.Id == Guid.Empty || !ActionConfigExists(ActionConfig.Id);

            if (isNew)
            {
                if (ActionConfig.Id == Guid.Empty)
                    ActionConfig.Id = Guid.NewGuid();


                _context.ActionConfigs.Add(ActionConfig);
            }
            else
            {
                // Update path
                _context.Attach(ActionConfig).State = EntityState.Modified;
            }

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ActionConfigExists(ActionConfig.Id))
                    return NotFound();

                throw;
            }

            return RedirectToPage("./Index");
        }

        private bool ActionConfigExists(Guid id)
        {
            return _context.ActionConfigs.Any(e => e.Id == id);
        }
    }
}

MagicButton/Pages/Device.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MagicButton.Data;
using MagicButton.Data.Models;

namespace MagicButton.Pages
{
    public class DeviceModel : PageModel
    {
        private readonly MagicButton.Data.MagicDbContext _context;

        public DeviceModel(MagicButton.Data.MagicDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public DeviceConfig DeviceConfig { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            var hasConfig = await _context.DeviceConfigs.AnyAsync();
            if (id == null && !hasConfig)
            {
                // CREATE mode
                DeviceConfig = new DeviceConfig
                {
                    // set any sensible defaults here if you want
                };
                return Page();
            }

            // EDIT mode

            var deviceconfig = await _context.DeviceConfigs.FirstOrDefaultAsync();
            DeviceConfig = deviceconfig;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var isNew = DeviceConfig.Id == Guid.Empty || !DeviceConfigExists(DeviceConfig.Id);
            if (isNew)
            {
                if (DeviceConfig.Id == Guid.Empty)
                    DeviceConfig.Id = Guid.NewGuid();

                _context.DeviceConfigs.Add(DeviceConfig);
            }
            else
            {
                _context.Attach(DeviceConfig).State = EntityState.Modified;
            }
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!DeviceConfigExists(DeviceConfig.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool DeviceConfigExists(Guid id)
        {
            return _context.DeviceConfigs.Any(e => e.Id == id);
        }
    }
}

MagicButton/Pages/Diagnostics.cshtml.cs
using MagicButton.Data;
using MagicButton.Data.Models;
using MagicButton.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Device.Gpio;

namespace MagicButton.Pages
{
    public class DiagnosticsModel : PageModel
    {

        private readonly MagicDbContext _context;
        private readonly BackgroundJobService _bj;
        public DiagnosticsModel(MagicDbContext context, BackgroundJobService bj)
        {                    
            _context = context;
            _bj = bj;
        }


        public int GreenPin { get; set; }
        public int RedPin { get; set; }
        public async Task OnGetAsync()
        {

            var greenPin = await _context.Leds.Where(x => x.Color == LedColor.Green).FirstOrDefaultAsync();
            if (greenPin != null)
            {
                GreenPin = greenPin.Pin;

            }

            var redPin = await _context.Leds.Where(x => x.Color == LedColor.Red).FirstOrDefaultAsync();
            if (redPin != null)
            {
                RedPin = redPin.Pin;

            }
        }

        public async Task OnGetApiTestAsync()
        {

            var device = await _context.DeviceConfigs.Include(x=>x.Actions).FirstOrDefaultAsync();
            if (device != null)
            {
                // Log or perform actions with the device
                Console.WriteLine($"API Test for Device ID: {device.DeviceId}");
                await _bj.HandleSinglePressAsync(device, _context, CancellationToken.None);
               
            }

            await OnGetAsync();
        }

    }
}

MagicButton/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MagicButton.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

MagicButton/Pages/Index.cshtml.cs
using MagicButton.Data;
using MagicButton.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System.Device.Gpio;
using System.Diagnostics;
namespace MagicButton.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly MagicDbContext _context;
        public IndexModel(ILogger<IndexModel> logger, MagicDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public bool isFirstRun { get; set; }

        public async Task OnGetAsync()
        {
            isFirstRun = await _context.DeviceConfigs.AnyAsync() == false;
        }

        public async Task OnGetCommandAsync(string action)
        {

            switch (action)
            {
                case "reboot":
                    {
                        _ = RunSudoAsync("reboot");
                        _logger.LogWarning("System reboot initiated via web command.");
                        break;
                    }
                case "shutdown":
                    {
                        _ = RunSudoAsync("shutdown", "-h", "now");
                        _logger.LogWarning("System shutdown initiated via web command.");
                        break;
                    }
                case "reset":
                    {
                        // Delete and recreate the database
                        try
                        {
                            await _context.Database.EnsureDeletedAsync();
                            await _context.Database.MigrateAsync();
                            _logger.LogWarning("Database reset initiated via web command.");
                        }
                        catch (Exception ex)
                        {
                            _logger.LogError(ex, "Error during database reset via web command.");
                        }
                        break;
                    }
                default:
                    break;
            }

        }

        private static Task RunSudoAsync(string command, params string[] args)
        {
            var psi = new ProcessStartInfo
            {
                FileName = "sudo",
                ArgumentList = { command },
                RedirectStandardOutput = true,
                RedirectStandardError = true,
                UseShellExecute = false
            };
            foreach (var a in args) psi.ArgumentList.Add(a);

            var p = new Process { StartInfo = psi, EnableRaisingEvents = false };
            p.Start();
            return Task.CompletedTask;
        }

    }
}

MagicButton/Pages/LEDs.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Device.Gpio;

namespace MagicButton.Pages
{
    public class LEDsModel : PageModel
    {
        public void OnGet()
        {
        }


    }
}

MagicButton/Pages/Led.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MagicButton.Data;
using MagicButton.Data.Models;

namespace MagicButton.Pages
{
    public class LedModel : PageModel
    {
        private readonly MagicButton.Data.MagicDbContext _context;

        public LedModel(MagicButton.Data.MagicDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Led Led { get; set; } = default!;
        public SelectList LedColours { get; set; }
        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            ViewData["DeviceConfigId"] = new SelectList(_context.DeviceConfigs, "Id", "DeviceId");

            var allColours = Enum.GetValues(typeof(LedColor)).Cast<LedColor>().ToList();   


            LedColours = new SelectList(allColours);


            if (id == null)
            {
                // CREATE mode
                Led = new Led
                {
                    // set any sensible defaults here if you want
                };

                var exitingColours = await _context.Leds.Select(x => x.Color).ToListAsync();

                foreach (var colour in exitingColours)
                {
                    allColours.Remove(colour);
                }

                return Page();
            }

            // EDIT mode

            var led = await _context.Leds.FindAsync(id);
            Led = led;

            
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more information, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            ViewData["DeviceConfigId"] = new SelectList(_context.DeviceConfigs, "Id", "DeviceId");

            var allColours = Enum.GetValues(typeof(LedColor)).Cast<LedColor>().ToList();



            if (!ModelState.IsValid)
            {
                LedColours = new SelectList(allColours);
                return Page();
            }
            var isNew = Led.Id == Guid.Empty || !LedExists(Led.Id);
            if (isNew)
            {
                if (Led.Id == Guid.Empty)
                    Led.Id = Guid.NewGuid();

                var existingPins = await _context.Leds.Select(x => x.Pin).ToListAsync();

                if (existingPins.Any(x => x == Led.Pin))
                {
                    // Duplicate pin
                    TempData["ErrorMessage"] = "Sorry but that GPIO Pin has already been added.";
                    LedColours = new SelectList(allColours);
                    return Page();
                }


                _context.Leds.Add(Led);
            }
            else
            {
                _context.Attach(Led).State = EntityState.Modified;
            }
            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!LedExists(Led.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            if (isNew)
            {
                TempData["SuccessMessage"] = "LED created successfully. Would you like to add another one just now?";
                LedColours = new SelectList(allColours);
                return RedirectToPage("./Led");
            }

            return RedirectToPage("./Index");
        }

        private bool LedExists(Guid id)
        {
            return _context.Leds.Any(e => e.Id == id);
        }
    }
}

MagicButton/Pages/Logs.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MagicButton.Pages
{
    public class LogsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

MagicButton/Pages/Press.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MagicButton.Data;
using MagicButton.Data.Models;

namespace MagicButton.Pages
{
    public class PressModel : PageModel
    {
        private readonly MagicButton.Data.MagicDbContext _context;

        public PressModel(MagicButton.Data.MagicDbContext context)
        {
            _context = context;
        }

        public ButtonPress ButtonPress { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var buttonpress = await _context.ButtonPresses.FirstOrDefaultAsync(m => m.Id == id);

            if (buttonpress is not null)
            {
                ButtonPress = buttonpress;

                return Page();
            }

            return NotFound();
        }
    }
}

MagicButton/Pages/Presses.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MagicButton.Data;
using MagicButton.Data.Models;

namespace MagicButton.Pages
{
    public class PressesModel : PageModel
    {
        private readonly MagicButton.Data.MagicDbContext _context;

        public PressesModel(MagicButton.Data.MagicDbContext context)
        {
            _context = context;
        }

        public IList<ButtonPress> ButtonPress { get;set; } = default!;

        public async Task OnGetAsync()
        {
            ButtonPress = await _context.ButtonPresses
                .Include(b => b.ActionConfig)
                .Include(b => b.DeviceConfig)
                .Include(b => b.Led).ToListAsync();
        }
    }
}

MagicButton/Pages/Action.cshtml
@page
@model MagicButton.Pages.ActionModel

@{
    var isNew = Model.ActionConfig == null || Model.ActionConfig.Id == Guid.Empty;
    ViewData["Title"] = isNew ? "Create Action" : "Edit Action";
}

<h1><i class="bi bi-boxes"></i> API Action</h1>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-gray p-2">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">API Action</li>
    </ol>
</nav>
<hr />
<div class="row">
    <div class="col-md-8 offset-md-2">
        <form method="post">
            @Html.AntiForgeryToken()
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="ActionConfig.Id" />

            <div class="form-group">
                <label asp-for="ActionConfig.DeviceConfigId" class="form-label">Button</label>
                <select asp-for="ActionConfig.DeviceConfigId"
                        class="form-select"
                        asp-items="@((SelectList)ViewData["DeviceConfigId"])">
                    <option value="">-- select device --</option>
                </select>
                <span asp-validation-for="ActionConfig.DeviceConfigId" class="text-danger"></span>
            </div>

            <div class="form-group">
                
                <label asp-for="ActionConfig.Kind" class="form-label"></label>
                <select asp-for="ActionConfig.Kind" class="form-select">
                    <option value="Single">Single Press</option>
                </select>
                <span asp-validation-for="ActionConfig.Kind" class="text-danger"></span>
            </div>
            <div class="form-group">
                
                <label asp-for="ActionConfig.Method" class="form-label"></label>
                <select asp-for="ActionConfig.Method" class="form-control" >
                    <option value="GET">GET</option>
                    <option value="POST">POST</option>
                </select>
                <span asp-validation-for="ActionConfig.Method" class="text-danger"></span>
            </div>
            <div class="form-group">
                
                <label asp-for="ActionConfig.Url" class="form-label"></label>
                <input asp-for="ActionConfig.Url" class="form-control" />
                <span asp-validation-for="ActionConfig.Url" class="text-danger"></span>
            </div>
            <div class="form-group">
                
                <label asp-for="ActionConfig.Headers" class="form-label">Headers (json)</label>
                <textarea asp-for="ActionConfig.Headers" class="form-control small-mono" rows="2" ></textarea>
                <span asp-validation-for="ActionConfig.Headers" class="text-danger"></span>
            </div>
            <div class="form-group">
                
                <label asp-for="ActionConfig.ExtraPayload" class="form-label">Payload (json)</label>
                <textarea asp-for="ActionConfig.ExtraPayload" class="form-control small-mono" rows="9"></textarea>
                <span asp-validation-for="ActionConfig.ExtraPayload" class="text-danger"></span>
            </div>
@*             <div class="form-group">
                
                <label asp-for="ActionConfig.RetriesMaxAttempts" class="form-label">Max retries on failure</label>
                <input asp-for="ActionConfig.RetriesMaxAttempts" class="form-control" />
                <span asp-validation-for="ActionConfig.RetriesMaxAttempts" class="text-danger"></span>
            </div>
            <div class="form-group">
                
                <label asp-for="ActionConfig.RetriesBaseDelayMs" class="form-label">Retry interval (ms)</label>
                <input asp-for="ActionConfig.RetriesBaseDelayMs" class="form-control" />
                <span asp-validation-for="ActionConfig.RetriesBaseDelayMs" class="text-danger"></span>
            </div>
            <div class="form-group">
                
                <label asp-for="ActionConfig.RetriesJitter" class="form-label">Retries jitter</label>
                <input asp-for="ActionConfig.RetriesJitter" class="form-control" />
                <span asp-validation-for="ActionConfig.RetriesJitter" class="text-danger"></span>
            </div> *@
            <div class="form-group">

                <button type="submit" class="btn btn-primary">
                    @(isNew ? "Create" : "Save")
                </button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MagicButton/Pages/Diagnostics.cshtml
@page
@model MagicButton.Pages.DiagnosticsModel
@{
    ViewData["Title"] = "Diagnostics";
}
<h1><i class="bi bi-boxes"></i> @ViewData["Title"]</h1>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-gray p-2">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Diagnostics</li>
    </ol>
</nav>
<hr />
@Html.AntiForgeryToken()
<div class="container py-4">

    <div class="border rounded p-3 mb-3">
        <h5 class="mb-3">API Test</h5>
        <p>
            Here you can test your API call.
            <a asp-page-handler="ApiTest" class="btn btn-primary">Send</a>
        </p>
    </div>
       
            @if (Model.GreenPin != 0 || Model.RedPin != 0)
            {
                <div class="border rounded p-3">
                    <h5 class="mb-3">LED Test</h5>
                    <p>
                        Here you can test your LEDs are wired and working as expected.
                        The buttons are momentary and need to be held down you can also use the keyboard:
                        <strong><code>Shift</code> <code>+</code> <code>R/G</code></strong>
                    </p>

                    <button class="btn btn-success btn-lg me-2"
                            data-pin="@Model.GreenPin"
                            hx-post="/gpio/on"
                            hx-vals='js:{"pin": this.dataset.pin}'
                            hx-trigger="mousedown, touchstart"
                            hx-target="this"
                            hx-swap="none"
                            hx-on:mouseup="htmx.ajax('POST','/gpio/off',{values:{pin:this.dataset.pin}})"
                            hx-on:mouseleave="htmx.ajax('POST','/gpio/off',{values:{pin:this.dataset.pin}})"
                            hx-on:touchend="htmx.ajax('POST','/gpio/off',{values:{pin:this.dataset.pin}})"
                            title="Shift+G to toggle while held">
                        💡 Green (pin @Model.GreenPin)
                    </button>

                    <!-- Red on pin 27 -->
                    <button class="btn btn-danger btn-lg"
                            data-pin="@Model.RedPin"
                            hx-post="/gpio/on"
                            hx-vals='js:{"pin": this.dataset.pin}'
                            hx-trigger="mousedown, touchstart"
                            hx-target="this"
                            hx-swap="none"
                            hx-on:mouseup="htmx.ajax('POST','/gpio/off',{values:{pin:this.dataset.pin}})"
                            hx-on:mouseleave="htmx.ajax('POST','/gpio/off',{values:{pin:this.dataset.pin}})"
                            hx-on:touchend="htmx.ajax('POST','/gpio/off',{values:{pin:this.dataset.pin}})"
                            title="Shift+R to toggle while held">
                        💡 Red (pin @Model.RedPin)
                    </button>
                </div>
            }
</div>
        @if (Model.GreenPin != 0 || Model.RedPin != 0)
        {
            @section Scripts {





            <script>
                let greenPin = @Model.GreenPin;
                let redPin = @Model.RedPin;

                // Avoid spamming repeated keydown while held
                const activeKeys = new Set();

                const map = [
                  { match: e => e.shiftKey && e.code === 'KeyG', pin: greenPin },
                  { match: e => e.shiftKey && e.code === 'KeyR', pin: redPin },
                ];

                document.addEventListener('keydown', e => {
                  const m = map.find(x => x.match(e));
                  if (!m) return;

                  const keySig = `${e.code}+shift`;
                  if (activeKeys.has(keySig)) return; // already ON
                  activeKeys.add(keySig);

                  htmx.ajax('POST', '/gpio/on', { values: { pin: m.pin } });
                });

                document.addEventListener('keyup', e => {
                  const m = map.find(x => x.match(e));
                  if (!m) return;

                  const keySig = `${e.code}+shift`;
                  if (!activeKeys.has(keySig)) return;
                  activeKeys.delete(keySig);

                  htmx.ajax('POST', '/gpio/off', { values: { pin: m.pin } });
                });

                // Safety: turn everything off when page unloads
                window.addEventListener('blur', () => {
                  activeKeys.forEach(sig => {
                    const code = sig.split('+')[0];
                    const m = map.find(x => `Key${x.pin === greenPin ? 'G' : x.pin === redPin ? 'R'}` === code);
                    if (m) htmx.ajax('POST', '/gpio/off', { values: { pin: m.pin } });
                  });
                  activeKeys.clear();
                });
            </script>


        }

        }

MagicButton/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

@if (Model.isFirstRun)
{
    <div class="text-center">

        <h4>Initial Setup</h4>
        <p>Welcome to your new Magic Buton!</p>


    </div>


    <p>To get started, please complete the following steps:</p>
    <ol>
        <li>Configure the <strong>Button</strong> settings</li>
        <li>Map and configure <strong>LEDs</strong></li>
        <li>Lastly, add your <strong>API Webhook</strong></li>
    </ol>

    <p class="border p-3 bg-light text-center">
        <a asp-page="/Device" class="btn btn-success btn-lg">Get Started</a>
    </p>

}
else
{
    <h4>Configure</h4>
    @await Html.PartialAsync("_NavTiles", new[]{
    ("API Action", "boxes", "/Action", "Configure the API Webhook action and payload", false, ""),
    ("Button Settings", "hand-index-thumb", "/Device", "Configure the intervals and thesholds", false, ""),
    ("LED Settings", "lightbulb", "/Leds", "Configure the response mappings", false, "")})
    <hr />
    <h4>Inspect</h4>
    @await Html.PartialAsync("_NavTiles", new[]{
    ("Action Log", "card-checklist", "/Presses", "View previous button presses", false, ""),
    ("Diagnostics", "gear-wide-connected", "/Diagnostics", "Test the LEDs and your API config", false, ""),
    ("System Log", "clipboard2-pulse", "/Logs", "View general system log", false, "")})
    <hr />
    <h4>Command</h4>
    @await Html.PartialAsync("_NavTiles", new[]{
    ("Factory Reset", "box-seam", "?handler=Command&action=reset", "Delete all data", true, "Are you sure?"),
    ("Reboot", "recycle", "?handler=Command&action=reboot", "Restart the system", true, "Are you sure?"),
    ("Shutdown", "door-closed", "?handler=Command&action=shutdown", "Controlled power off", true, "Are you sure?")})
}

MagicButton/Pages/LEDs.cshtml
@page
@model MagicButton.Pages.LedsModel

@{
    ViewData["Title"] = "LEDs";
}

<h1><i class="bi bi-boxes"></i> @ViewData["Title"]</h1>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-gray p-2">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">LED Settings</li>
    </ol>
</nav>
<hr />

<p>
    <a class="btn btn-primary" asp-page="Led">Create New</a>
</p>
<table class="table table-striped">
    <thead class="table-dark">
        <tr>
            <th>LED Colour</th>
            <th>Friendly Name</th>
            <th>GPIO Pin</th>
            <th>Active Low?</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Led)
        {
            <tr>
                <td class="fw-bold">
                    <a asp-page="Led" asp-route-id="@item.Id">@item.Color</a>
                </td>
                <td>
                    @item.Name
                </td>
                <td>
                    <span class="badge bg-success fs-5 font-monospace">@item.Pin</span>
                </td>
                <td>
                    @if (item.ActiveLow)
                    {

                       <span class="text-success">✅ Yes</span>

                    }
                    else
                    {

                        <span class="text-danger">⛔ No</span>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

MagicButton/Pages/Presses.cshtml
@page
@model MagicButton.Pages.PressesModel

@{
    ViewData["Title"] = "Action Log";
}

<h1><i class="bi bi-boxes"></i> @ViewData["Title"]</h1>
<nav aria-label="breadcrumb">
    <ol class="breadcrumb bg-gray p-2">
        <li class="breadcrumb-item"><a href="/">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Action Log</li>
    </ol>
</nav>
<hr />

<table class="table table-striped">
    <thead>
        <tr class="table-dark">
            <th>Timestamp</th>
            <th>Action</th>
            <th>Duration</th>
            <th>Response</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.ButtonPress)
        {
            <tr>
                <td><a asp-page="Press" asp-route-id="@item.Id">@item.PressedAtUtc.ToString("dd/MM/yyyy")</a></td>
                <td>@item.ActionConfig?.Url</td>
                <td>@(item.DurationMs + " ms")</td>
                <td>
                    @if (item.ResponseStatusCode.HasValue && item.ResponseStatusCode.Value.ToString().StartsWith("5"))
                    {
                        <span class="badge bg-danger">@item.ResponseStatusCode</span>
                    }
                    else
                    {
                        <span class="badge bg-light">@item.ResponseStatusCode</span>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>